name: neural-graphics
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=11.8
  - numpy
  - pip:
      - opencv-python
      - pudb
      - imageio
      - imageio-ffmpeg
      - pytorch-lightning==2.0.0
      - omegaconf
      - einops
      - torch-fidelity
      - transformers
      - configargparse
      - lmdb
      - tensorboardX
      - tensorboard
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e .