module:
  target: models.classification.EIPS
  params:
    margin: 2.5
    lr: 2e-5
    weight_decay: 0.
    net_config:
      target: models.classification.SwinTransformer
      params:
        in_channels: 3
        in_res: 512
        window_size: 16
        patch_size: 4
        hidden_dims: [ 32, 64, 128, 256 ]
        embed_dim: 16
        quant_dim: 8
        logit_dim: 1
        num_blocks: [ 1, 1, 3, 1 ]
        num_groups: 16
        num_heads: [ 4, 8, 16, 16 ]
        dropout: 0.0
        attn_dropout: 0.0
        drop_path: 0.1
        qkv_bias: True
        bias: True
        act: 'gelu'
        use_conv: True
        pool_type: 'conv'
        dim: 2
        use_checkpoint: True
        attn_mode: 'cosine'
        use_norm: True
        lr: 2e-5
        weight_decay: 0.
        ckpt_path: './checkpoints/classification/arknights100_best.ckpt'

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsTripletDataset
      params:
        root: '/local_datasets/arknights100'
        train: True
        size: 512
        scale: [0.5, 1.0]
        ratio: [1.0, 1.0]
        color_space: 'rgb'

    validation:
      target: modules.datasets.arknights.ArknightsTripletDataset
      params:
        root: '/local_datasets/arknights100'
        train: False
        size: 512
        scale: [ 0.5, 1.0 ]
        ratio: [ 1.0, 1.0 ]
        color_space: 'rgb'


logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'eips'
    version: 'arknights100'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/eips/'
      filename: 'arknights100'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/eips/'
      filename: 'arknights100_best'
      monitor: 'val/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 500
  accumulate_grad_batches: 5