module:
  target: models.classification.EIPS
  params:
    num_heads: 8
    window_size: 8
    bias: True
    dropout: 0.
    attn_dropout: 0.
    drop_path: 0.0
    act: 'gelu'
    num_groups: 32
    use_conv: True
    attn_mode: 'cosine'
    dim: 2
    lr: 2e-5
    weight_decay: 0.
    log_interval: 100

    encoder_img_config:
      target: models.reconstruction.ReconNet
      params:
        lr: 2e-5
        weight_decay: 0.0
        lr_decay_epoch: 100
        use_fp16: False
        log_interval: 100
        ckpt_path: './checkpoints/recon/imagenet.ckpt'
        net_config:
          target: modules.blocks.UNet
          params:
            in_channels: 3
            in_res: 512
            window_size: 8
            out_channels: 3
            embed_dim: 32
            hidden_dims: [ 64, 64, 128, 128, 256, 256, 512 ]
            num_blocks: 1
            num_heads: [ 2, 2, 4, 4, 8, 8, 16 ]
            dropout: 0.0
            attn_dropout: 0.0
            drop_path: 0.0
            qkv_bias: True
            bias: True
            num_groups: 32
            act: 'gelu'
            use_conv: True
            mode: 'nearest'
            dim: 2
            use_checkpoint: True
            attn_mode: 'cosine'
            use_residual_attention: True
    encoder_edge_config:
      target: models.reconstruction.ReconNet
      params:
        lr: 2e-5
        weight_decay: 0.0
        lr_decay_epoch: 100
        use_fp16: False
        log_interval: 100
        ckpt_path: './checkpoints/recon/edge.ckpt'
        net_config:
          target: modules.blocks.UNet
          params:
            in_channels: 3
            in_res: 512
            window_size: 8
            out_channels: 3
            embed_dim: 32
            hidden_dims: [ 64, 64, 128, 128, 256, 256, 512 ]
            num_blocks: 1
            num_heads: [ 2, 2, 4, 4, 8, 8, 16 ]
            dropout: 0.0
            attn_dropout: 0.0
            drop_path: 0.0
            qkv_bias: True
            bias: True
            num_groups: 32
            act: 'gelu'
            use_conv: True
            mode: 'nearest'
            dim: 2
            use_checkpoint: True
            attn_mode: 'cosine'
            use_residual_attention: True

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsImageEdgeSimilarity
      params:
        root: '/local_datasets/arknights100'
        train: True
        size: 512
        scale: [0.5, 1.0]
        ratio: [1.0, 1.0]
        color_space: 'rgb'

    validation:
      target: modules.datasets.arknights.ArknightsImageEdgeSimilarity
      params:
        root: '/local_datasets/arknights100'
        train: False
        size: 512
        scale: [ 0.5, 1.0 ]
        ratio: [ 1.0, 1.0 ]
        color_space: 'rgb'


logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'eips'
    version: 'arknights100'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/eips/'
      filename: 'arknights100'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/eips/'
      filename: 'arknights100_best'
      monitor: 'val/dist_pos'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 500
  accumulate_grad_batches: 5