module:
  target: models.classification.EIPS
  params:
    in_channels: 3
    in_res: 512
    mlp_ratio: 4.0
    window_size: 8
    embed_dim: 32
    hidden_dims: [64, 96, 128, 160, 192, 224, 256]
    num_blocks: 1
    num_heads: -1
    num_head_channels: 32
    dropout: 0.0
    attn_dropout: 0.0
    drop_path: 0.1
    qkv_bias: True
    bias: True
    num_groups: 16
    act: 'gelu'
    pool_type: 'conv'
    use_conv: True
    dim: 2
    use_checkpoint: True
    attn_mode: 'cosine'
    lr: 2e-5
    weight_decay: 1e-4
    log_interval: 2
    margin: 0.5

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsImageEdgeSimilarity
      params:
        root: '/local_datasets/arknights100'
        train: True
        size: 512
        scale: [0.5, 1.0]
        ratio: [1.0, 1.0]
        color_space: 'rgb'

    validation:
      target: modules.datasets.arknights.ArknightsImageEdgeSimilarity
      params:
        root: '/local_datasets/arknights100'
        train: False
        size: 512
        scale: [ 0.5, 1.0 ]
        ratio: [ 1.0, 1.0 ]
        color_space: 'rgb'


logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'eips'
    version: 'arknights100'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/eips/arknights100'
      filename: 'eips'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/eips/arknights100'
      filename: 'eips_best'
      monitor: 'val/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 500
  accumulate_grad_batches: 25