module:
  target: models.classification.EIPS
  params:
    in_channels: 3
    in_res: 512
    mlp_ratio: 4.0
    window_size: 8
    embed_dim: 32
    hidden_dims: [64, 96, 128, 160, 192, 224, 256]
    num_blocks: 1
    num_heads: -1
    num_head_channels: 32
    dropout: 0.0
    attn_dropout: 0.0
    drop_path: 0.1
    qkv_bias: True
    bias: True
    num_groups: 16
    act: 'gelu'
    pool_type: 'conv'
    use_conv: True
    dim: 2
    use_checkpoint: True
    attn_mode: 'cosine'
    lr: 2e-5
    weight_decay: 0.0
    log_interval: 2
    margin: 0.5
    ckpt_path: './checkpoints/eips/arknights100/eips_best.ckpt'