module:
  target: models.classification.EIPS
  params:
    in_channels: 3
    in_res: 224
    patch_size: 4
    window_size: 7
    hidden_dims: [64, 128, 256, 256]
    embed_dim: 32
    attn_res: [0, 1, 2, 3]
    num_blocks: 4
    num_dense_blocks: 4
    num_heads: 8
    mlp_ratio: 4
    dropout: 0.0
    attn_dropout: 0.0
    drop_path: 0.0
    qkv_bias: True
    bias: True
    attn_mode: 'cosine'
    num_groups: 16
    act: 'gelu'
    use_conv: True
    pool_type: 'max'
    lr: 2e-5
    weight_decay: 0.
    lr_decay_epoch: 100
    dim: 2
    use_checkpoint: True
    # ckpt_path: './checkpoints/eips/arknights_v2.ckpt'
    criterion_config:
      target: utils.loss.EuclideanDistanceWithCosineDistance
      params:
        use_square: True
        use_normalize: True
        ed_weight: 1.0
        ed_dim: [2, 3]
        cd_weight: 1.0
        cd_dim: 1
        reduction: 'mean'

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsTripletDataset
      params:
        root: '/local_datasets/arknights_v2'
        # root: './datasets/arknights_v2'
        train: True
        size: 224

    validation:
      target: modules.datasets.arknights.ArknightsTripletDataset
      params:
        root: '/local_datasets/arknights_v2'
        # root: './datasets/arknights_v2'
        train: False
        size: 224

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'eips'
    version: 'arknights_v2'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/eips/'
      filename: 'arknights_v2'
      monitor: 'val/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 20
  accumulate_grad_batches: 5