module:
  target: models.vae.frequency_vae.FrequencyVAE
  params:
    in_channels: 3
    out_channels: 3
    hidden_dims: [64, 128, 128, 256, 512, 512]
    latent_dim: 4
    z_channels: 4
    num_res_blocks: 2
    num_head_channels: 32
    dim: 2
    act: 'gelu'
    kl_weight: 1e-5
    lr: 2e-5
    weight_decay: 0.
    freq_pass_eps: 0.25
    high_freq_weight: 2.0
    low_freq_weight: 1.0
    log_interval: 100
    perceptual_weight: 1.0

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 2
    batch_size: 1
    wrap: True
    train:
      target: modules.datasets.genshin_impact.GenshinImpactDataset
      params:
        root: '/local_datasets/genshin_impact'
        train: True
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 960, 960 ]
    validation:
      target: modules.datasets.genshin_impact.GenshinImpactDataset
      params:
        root: '/local_datasets/genshin_impact'
        train: False
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 960, 960 ]


logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'freqVAE'
    version: 'default'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/freqVAE/default'
      filename: 'freqVAE'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/freqVAE/default'
      filename: 'freqVAE'
      monitor: 'val/freq_loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 5