module:
  target: models.enet.enet.EdgeNet
  params:
    in_channels: 3
    in_res: 512
#    disc_config:
#      target: models.gan.discriminator.Discriminator
#      params:
#        in_channels: 4
#        embed_dim: 64
#        num_layers: 3
#        bias: False
    out_channels: 1
    hidden_dims: [32, 64, 96, 128]
    embed_dim: 16
    num_blocks: 2
    # attn_res: [3]
    num_heads: 8
    mlp_ratio: 4
    dropout: 0.
    attn_dropout: 0.
    bias: True
    groups: 4
    act: 'silu'
    use_conv: False
    pool_type: 'max'
    mode: 'nearest'
    lr: 2e-5
    weight_decay: 0.
    disc_weight: 1
    disc_factor: 1.
    disc_iter_start: 20001
    disc_loss: 'hinge'
    log_interval: 100
#    bdr_factor: [0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.01]
#    tex_factor: [2., 2., 2., 1., 1., 1., 4.]
    l_weight: [0.7, 0.7, 1.1, 1.1, 0.3, 0.3, 1.3]

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 1
    batch_size: 1
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: True
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]
    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: False
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'edgenet'
    version: 'test'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/edgenet/test'
      filename: 'edgenet'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 500