module:
  target: models.enet.enet.EdgeNet
  params:
    in_channels: 3
    in_res: 512
    loss_config:
      target: modules.loss.edge_perceptual.EdgePerceptualLoss
      params:
        l1_weight: 0.5
        cats_weight: [1.0, 0.05, 1.]
        perceptual_weight: 1.0
        contents_weight: 0.25

    patch_size: 4
    window_size: 8
    out_channels: 1
    hidden_dims: [32, 64, 96, 96]
    embed_dim: 16
    num_blocks: 4
    num_head_channels: 8
    mlp_ratio: 2
    dropout: 0.1
    attn_dropout: 0.1
    drop_path: 0.1
    qkv_bias: True
    bias: True
    groups: 8
    act: 'silu'
    use_conv: True
    pool_type: 'max'
    mode: 'nearest'
    lr: 2e-5
    weight_decay: 0.
    lr_decay_epoch: 100
    dim: 2

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 2
    batch_size: 1
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        # root: './datasets/arknights'
        train: True
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]
    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        # root: './datasets/arknights'
        train: False
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'edgenet'
    version: 'test2'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/edgenet/test2'
      filename: 'edgenet'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 50