module:
  target: models.enet.enet.EDNSE
  params:
    lr: 2e-5
    weight_decay: 1e-4
    lr_decay_epoch: 100
    use_fp16: False
    log_interval: 10
    # ckpt_path: './checkpoints/ednse/arknights_unet/ednse-v1.ckpt'

    net_config:
      target: modules.blocks.UNet
      params:
        in_channels: 3
        in_res: 512
        window_size: 8
        out_channels: 1
        hidden_dims: [ 32, 64, 96, 128 ]
        embed_dim: 16
        attn_res: [ 0, 1, 2, 3]
        num_blocks: 2
        # num_heads: -1
        num_head_channels: 8
        mlp_ratio: 4
        dropout: 0.0
        attn_dropout: 0.0
        drop_path: 0.0
        qkv_bias: True
        bias: True
        num_groups: 8
        act: 'gelu'
        use_conv: True
        pool_type: 'max'
        mode: 'nearest'
        dim: 2
        use_checkpoint: True
        attn_mode: 'cosine'
        use_addition_skip: False
        use_lpf_conv: False
        perception_level: 2

    loss_config:
      target: modules.loss.edge_perceptual.EdgePerceptualLoss
      params:
        pn_weight: 1.0
        l1_weight: 1.0
        perceptual_weight: 1.0
        edge_image_perceptual_weight: 0.05
        eips_config:
          lr: 2e-5
          weight_decay: 0.0
          lr_decay_epoch: 100
          use_fp16: False
          log_interval: 10
          margin: 2.0
          use_deep_supervision: True
          mean_img: [ 0.5965, 0.5498, 0.5482 ]
          std_img: [ 0.2738, 0.2722, 0.2641 ]
          mean_edge: 0.9085
          std_edge: 0.2184
          ckpt_path: './checkpoints/eips/arknights.ckpt'

          net_config:
            target: modules.blocks.SwinEncoder
            params:
              in_channels: 3
              in_res: 512
              window_size: 8
              patch_size: 4
              hidden_dims: [ 64, 128, 256, 256 ]
              embed_dim: 32
              attn_res: [ 0, 1, 2, 3 ]
              num_blocks: 2
              num_heads: -1
              num_head_channels: 16
              mlp_ratio: 4
              dropout: 0.0
              attn_dropout: 0.0
              drop_path: 0.0
              qkv_bias: True
              bias: True
              num_groups: 32
              act: 'gelu'
              use_conv: True
              pool_type: 'max'
              dim: 2
              use_checkpoint: True
              attn_mode: 'cosine'

          criterion_config:
            target: utils.loss.EuclideanDistanceWithCosineDistance
            params:
              use_square: True
              use_normalize: True
              ed_weight: 1.0
              ed_dim: [ 2, 3 ]
              cd_weight: 1.0
              cd_dim: 1
              reduction: 'mean'
data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: True
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]

    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: False
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'ednse'
    version: 'arknights_unet'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/ednse/arknights_unet'
      filename: 'ednse_last'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/ednse/arknights_unet'
      filename: 'ednse_best'
      monitor: 'val/eip_loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 100
  accumulate_grad_batches: 5