module:
  target: models.enet.enet.EdgeNet
  params:
    lr: 2e-5
    weight_decay: 1e-4
    lr_decay_epoch: 100
    use_fp16: False
    log_interval: 20
    # ckpt_path: './checkpoints/edgenet/arknights/edgenet.ckpt'

    net_config:
      target: models.enet.enet.EDNSE
      params:
        in_channels: 3
        in_res: 512
        window_size: 8
        out_channels: 1
        hidden_dims: [ 32, 64, 96]
        embed_dim: 16
        attn_res: [ 0, 1, 2 ]
        num_blocks: 4
        num_heads: 8
        mlp_ratio: 4
        dropout: 0.0
        attn_dropout: 0.0
        drop_path: 0.0
        qkv_bias: True
        bias: True
        num_groups: 16
        act: 'gelu'
        use_conv: True
        pool_type: 'max'
        mode: 'nearest'
        dim: 2
        use_checkpoint: True
        attn_mode: 'cosine'

    loss_config:
      target: modules.loss.edge_perceptual.EdgePerceptualLoss
      params:
        bdcn_weight: 1.1
        cats_weight: [ 1.0, 0.05, 1. ]
        l1_weight: 1.0
        perceptual_weight: 1.0
        contents_weight: 0.8
data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: True
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.RandomCrop
              params:
                size: [ 512, 512 ]

    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: False
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.RandomCrop
              params:
                size: [ 512, 512 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'ednse'
    version: 'arknights_unet'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/ednse/arknights_unet'
      filename: 'ednse'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 200
  accumulate_grad_batches: 5