module:
  target: models.enet.enet.EdgeNet
  params:
    in_channels: 3
    in_res: 512
    loss_config:
      target: modules.loss.edge_perceptual.EdgePerceptualLoss
      params:
        disc_start: 20001
        disc_embed_dim: 64
        disc_num_layers: 3
        disc_in_channels: 1
        d_weight: 1.0
        g_weight: 1e-4
        l1_weight: 1.0
        perceptual_weight: 1.0
        disc_loss: "hinge"

    patch_size: 4
    window_size: 8
    out_channels: 1
    hidden_dims: [32, 64, 96]
    embed_dim: 16
    num_blocks: 3
    num_heads: 8
    mlp_ratio: 4
    dropout: 0
    attn_dropout: 0
    drop_path: 0
    qkv_bias: True
    bias: True
    groups: 4
    act: 'gelu'
    use_conv: False
    pool_type: 'max'
    mode: 'nearest'
    lr: 2e-5
    weight_decay: 0.
    # l_weight: [0.01, 4.]
    l_weight: [ [ 0.05, 2. ], [ 0.05, 2. ], [ 0.05, 2. ], [ 0.1, 1. ], [ 0.1, 1. ], [ 0.1, 1. ], [ 0.01, 4. ] ]
    dim: 2

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 1
    batch_size: 1
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: True
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]
    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: False
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'edgenet'
    version: 'test'


checkpoints:
  latest_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/edgenet/test'
      filename: 'edgenet'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 500