module:
  target: models.enet.enet.EDNSE
  params:
    lr: 2e-5
    weight_decay: 1e-4
    lr_decay_epoch: 100
    use_fp16: False
    log_interval: 10
    threshold: 0.5
    color_space: 'lab'

    net_config:
      target: modules.blocks.UNet
      params:
        in_channels: 3
        in_res: 512
        window_size: 8
        out_channels: 1
        hidden_dims: [ 64, 96, 128, 160 ]
        embed_dim: 32
        attn_res: [ 0, 1, 2, 3 ]
        num_blocks: 2
        num_heads: 8
        num_head_channels: -1
        mlp_ratio: 4
        dropout: 0.0
        attn_dropout: 0.0
        drop_path: 0.0
        qkv_bias: True
        bias: True
        num_groups: 32
        act: 'gelu'
        use_conv: True
        pool_type: 'max'
        mode: 'nearest'
        dim: 2
        use_checkpoint: True
        attn_mode: 'cosine'
        use_addition_skip: False
        use_lpf_conv: False
        perception_level: 2

    loss_config:
      target: modules.loss.edge_perceptual.EdgePerceptualLoss
      params:
        bdcn_weight: 1.2
        l1_weight: 1.0
        lpips_weight: 1.0
        eips_weight: 0.03
#        eips_config:
#          lr: 2e-5
#          weight_decay: 0.0
#          lr_decay_epoch: 100
#          use_fp16: False
#          log_interval: 10
#          margin: 0.5
#          use_deep_supervision: False
#          ckpt_path: './checkpoints/eips/arknights100_best.ckpt'
#
#          net_config:
#            target: modules.blocks.SwinEncoder
#            params:
#              in_channels: 3
#              in_res: 512
#              window_size: 8
#              patch_size: 4
#              hidden_dims: [ 64, 128, 256, 256 ]
#              embed_dim: 32
#              attn_res: [ 0, 1, 2, 3 ]
#              num_blocks: 2
#              num_heads: 8
#              num_head_channels: -1
#              mlp_ratio: 4
#              dropout: 0.1
#              attn_dropout: 0.1
#              drop_path: 0.0
#              qkv_bias: True
#              bias: True
#              num_groups: 32
#              act: 'gelu'
#              use_conv: True
#              pool_type: 'max'
#              dim: 2
#              use_checkpoint: True
#              attn_mode: 'cosine'
#
#          criterion_config:
#            target: utils.loss.CosineDistance
#            params:
#              dim: 1

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights100'
        train: True
        size: 512
        scale: [ 0.5, 1.0 ]
        ratio: [ 1.0, 1.0 ]
        color_space: 'lab'

    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights100'
        train: False
        size: 512
        scale: [ 0.5, 1.0 ]
        ratio: [ 1.0, 1.0 ]
        color_space: 'lab'

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'ednse'
    version: 'arknights_unet'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/ednse/'
      filename: 'arknights_unet_last'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/ednse/'
      filename: 'arknights_unet_best'
      monitor: 'val/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 400
  accumulate_grad_batches: 5