module:
  target: models.edge.sd.SketchDetectionNetwork
  params:
    in_channels: 3
    out_channels: 1
    embed_dim: 16
    hidden_dims: [ 32, 64, 128, 256 ]
    num_blocks: 1
    dropout: 0.0
    drop_path: 0.0
    deformable_group_channels: 16
    offset_scale: 1.0
    modulation_type: 'none'
    dw_kernel_size: 7
    num_groups: 16
    act: 'gelu'
    use_conv: True
    pool_type: 'conv'
    mode: 'nearest'
    dim: 2
    use_checkpoint: True
    lr: 2e-5
    weight_decay: 0.0
    lr_decay_epoch: 100
    log_interval: 10
    ckpt_path: './checkpoints/sd/arknights/sd_train.ckpt'

    loss_config:
      target: modules.loss.edge_perceptual.EdgeLPIPSWithDiscriminator
      params:
        bdcn_weight: 1.0
        lpips_weight: 1.0
        balanced_l1_weight: 1.0
        cats_weight: [1.0, 0.0, 1.2]
        content_weight: 0.5

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 4
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/anime'
        # root: './datasets/anime'
        train: True
        size: 512
        color_space: 'rgb'
        scale: [0.5, 1.0]

    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/anime'
        # root: './datasets/anime'
        train: False
        size: 512
        color_space: 'rgb'
        scale: [0.5, 1.0]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'sd'
    version: 'arknights'


checkpoints:
  latest_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/sd/arknights'
      filename: 'sd'
      monitor: 'step'
      mode: 'max'
      save_top_k: 1

  train_checkpoints:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/sd/arknights'
      filename: 'sd_train'
      monitor: 'train/total_loss'
      mode: 'min'
      save_top_k: 1

  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/sd/arknights'
      filename: 'sd_best'
      monitor: 'val/total_loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 300
  accumulate_grad_batches: 5