module:
  target: models.enet.enet.EDNSE
  params:
    lr: 2e-5
    weight_decay: 0.0
    lr_decay_epoch: 100
    use_fp16: False
    log_interval: 50
    accumulate_grad_batches: 5
    disc_update_freq: 2
    ckpt_path: './checkpoints/ednse/test/arknights_unet_best.ckpt'
    ignore_keys: ['loss']
    net_config:
      target: modules.blocks.UNet
      params:
        in_channels: 3
        in_res: 512
        window_size: 8
        out_channels: 1
        embed_dim: 16
        hidden_dims: [ 32, 32, 64, 64, 128, 128, 256]
        num_blocks: 2
        num_heads: [ 2, 2, 4, 4, 8, 8, 16]
        dropout: 0.0
        attn_dropout: 0.0
        drop_path: 0.0
        qkv_bias: True
        bias: True
        num_groups: 16
        act: 'gelu'
        use_conv: True
        pool_type: 'conv'
        mode: 'nearest'
        dim: 2
        use_checkpoint: True
        attn_mode: 'cosine'
