module:
  target: models.edge_detection.ldc.LDC
  params:
    in_channels: 3
    embed_dim: 16
    hidden_dims: [32, 64, 96]
    num_blocks: 2
    num_downs: 2
    use_conv: False
    pool_type: 'max'
    mode: 'nearest'
    use_norm: True
    num_groups: 4
    use_act: True
    act: 'silu'
    dim: 2
    lr: 2e-5
    weight_decay: 0.
    log_interval: 50

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 1
    batch_size: 2
    wrap: True
    train:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: True
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]
    validation:
      target: modules.datasets.arknights.ArknightsDataset
      params:
        root: '/local_datasets/arknights'
        train: False
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 512, 512 ]

logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'ldc'
    version: 'test'


checkpoints:
  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/ldc/test'
      filename: 'ldc'
      monitor: 'val/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 100