module:
  target: models.enet.enet.EDNSE
  params:
    lr: 2e-5
    weight_decay: 0.0
    lr_decay_epoch: 100
    use_fp16: False
    log_interval: 50
    accumulate_grad_batches: 10
    ckpt_path: './checkpoints/ednse/arknights_unet/ednse_best.ckpt'
    net_config:
      target: modules.blocks.UNet
      params:
        in_channels: 3
        in_res: 512
        window_size: 8
        out_channels: 1
        embed_dim: 32
        hidden_dims: [ 64, 64, 128, 128, 256, 256 ]
        num_blocks: 1
        num_heads: 8
        num_head_channels: -1
        dropout: 0.0
        attn_dropout: 0.0
        drop_path: 0.0
        qkv_bias: True
        bias: True
        mlp_ratio: 4.0
        num_groups: 32
        act: 'gelu'
        use_conv: True
        pool_type: 'conv'
        mode: 'bilinear'
        dim: 2
        use_checkpoint: True
        attn_mode: 'cosine'
