module:
  target: modules.loss.lpips.LPIPS
  params:
    net_type: 'swin_v2_t'
    dropout: 0.5
    lr: 2e-5
    weight_decay: 0.0

    loss_config:
      chn_mid: 32

data:
  target: modules.datasets.util.DataModuleFromConfig
  params:
    num_workers: 2
    batch_size: 50
    wrap: True
    train:
      target: modules.datasets.twoafc.TwoAFCDataset
      params:
        root: '/local_datasets/twoafc'
        train: True
        subdirs: ['traditional', 'cnn', 'mix']
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 64, 64 ]

    validation:
      target: modules.datasets.twoafc.TwoAFCDataset
      params:
        root: '/local_datasets/twoafc'
        train: False
        subdirs: ['traditional', 'cnn', 'superres', 'deblur', 'color', 'frameinterp']
        transform_configs:
          transforms:
            - target: torchvision.transforms.transforms.ToTensor
            - target: torchvision.transforms.transforms.Resize
              params:
                size: [ 64, 64 ]


logger:
  target: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  params:
    save_dir: './logs'
    name: 'lpips'
    version: 'swin_v2_t'


checkpoints:
  best_checkpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: './checkpoints/lpips/swin_v2_t'
      filename: 'lpips'
      monitor: 'val/loss'
      mode: 'min'
      save_top_k: 1

trainer:
  accelerator: 'gpu'
  max_epochs: 20
  # gradient_clip_val: 0